[package]
name = "dapr-macros"
version = "0.15.1-rc.1"
edition = "2021"
description = "Dapr Rust SDK"
license = "Apache-2.0"

[lib]
proc-macro = true

[dependencies]
async-trait = "0.1"
log = "0.4"
axum = "0.7.4"
syn = { version = "2.0.29", features = ["full"] }
quote = "1.0.8"
proc-macro2 = "1.0"
